apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: microservices
type: Opaque
data:
  DB_USER: <base64-encoded-db-user>
  DB_PASS: <base64-encoded-db-pass>
  DB_HOST: <base64-encoded-db-host>
  DB_NAME: <base64-encoded-db-name>
